
// Main Actions
export const STATE_ACTIONS: Record<string, string> = {
    SET_USER: 'SET_USER',
    LOGIN_OUT: 'LOGIN_OUT',
    SET_CONTRACTS_SUMMARY: 'SET_CONTRACTS_SUMMARY',
    UPDATE_CONTRACT_ON_SUMMARY: 'UPDATE_CONTRACT_ON_SUMMARY',
    SET_CONTRACT_SUMMARY: 'SET_CONTRACT_SUMMARY',
    REMOVE_CONTRACT_SUMMARY: 'REMOVE_CONTRACT_SUMMARY'
}

// Routes Actions
export const ROUTES_ACTIONS: Record<string, string> = {
    ACTIVE_ROUTE: 'ACTIVE_ROUTE',
    UPDATE_ROUTE: 'UPDATE_ROUTE'
}